name = "day2"
description = ""
version = "0.1.0-dev"

authors = ["Corentin Guilloteau"]
maintainers = ["Corentin Guilloteau <corentin.gu@gmail.com>"]
licenses = "MIT"
website = ""
tags = []

executables = ["main"]
